### ISSUE TITLE
📄 Align the organisation README with the project, before this repo is archived

### ISSUE THREAD

**Issue by janhalen** [OS2fleetoptimiser/project-setup#10]
## 🎯 Objective
Make sure that https://github.com/OS2fleetoptimiser is a relevant and up to date after archiving this repo.

The README should:

- Provide an overview of the organization
- Convey the mission, values, and work of the project
- Guide visitors to more detailed information
- Establish a consistent and professional image to attract users and contributors to the 
 project
-  Set the tone for the projects commitment to quality, transparency, and collaboration

**Comment by janhalen** [comment]
This would be a ideal "good first issue" for onboarding the PO with a practical task.

This guide might serve as a entry point: https://www.tukutoi.com/creating-a-stellar-github-readme-for-your-organization/

**Comment by janhalen** [comment]
We agreed to mirror the Os2Compliance "simple setup" and postpone a better and more expanded introduction to q1 2025

**Comment by andreasDroid** [comment]
@janhalen , I don't have any rights on the main organisation page to setup the temporary _simple setup_

**Comment by janhalen** [comment]
Access fixed!
