### ISSUE TITLE
👓 Make the documentation more accesible

### ISSUE THREAD

**Issue by janhalen** [OS2fleetoptimiser/project-setup#12]
## 🎯 Objectives

- Increased visibility - Ensures users can easily find the documentation regardless of where they find or access the project
- Improved accessibility - Create multiple entry points make it easier for different types of users to access the information they need
- Better user experience: Clear links to documentation help users quickly understand and use the project.

Right now, there is no direct links to the rendered version of the Documentation located here: https://os2fleetoptimiser.github.io/OS2fleetoptimiser-docs/

**Comment by janhalen** [comment]
@andreasDroid: I suggest as a minimum linking from 

- the Org. readme (that will then be a part of #10 )
- the source and docs repo READMEs

If you think the chore is worth it, we can also add the link to some of the repos metadata, by manually opdating it in the GitHub UI (annoying as it might be)

**Comment by andreasDroid** [comment]
@janhalen , the https://os2fleetoptimiser.github.io/OS2fleetoptimiser-docs is linked in the readme.md and readme_da.md as "FleetOptimiser Documentation". 

But we can move that up or reference it earlier or more in the readme. 
I guess, I should not be the one writing up the Orgs readme :)

**Comment by janhalen** [comment]
I think this is a great issue for @sobuos to evaluate.. If its valuable or not relevant right now.. 

Right now the organisation page, signifies a product in ist early days.. https://github.com/os2fleetoptimiser

So how a good entrypoint would look for developers, descission makers etc. should be discussed.

**Comment by janhalen** [comment]
Marked as "TBD" later
