### ISSUE TITLE
🗣️ Project setup backlog status

### ISSUE THREAD

**Issue by janhalen** [OS2fleetoptimiser/project-setup#13]
## 🎯 Objective:

Finish the tasks outlined in the project-setup issue tracker.

**Comment by janhalen** [comment]
@sobuos & @andreasDroid: Should we have a quick evaluation of the remaining issues in the project-setup?

Should we schedule a quick "backlog management" standup, maybe if you allready have a meeting planned i could just join for 15 mins?

**Comment by andreasDroid** [comment]
Sounds good to me. 
We have a catch up tomorrow at 900-920, perhaps we can do it afterwards if you're both available?

**Comment by sobuos** [comment]
@andreasDroid you mean Thursday, right? I will schedule 15 minutes after our meeting with the project group

**Comment by andreasDroid** [comment]
> @andreasDroid you mean Thursday, right? I will schedule 15 minutes after our meeting with the project group

Yes, sorry :) Thursday!

**Comment by janhalen** [comment]
Perfect, thursday 05 dec 9:20 it is.... 

I'll log our decisions here in this issue... See you thursday!

@zorp: If you have interrest in a quick status, sobuos can invite you to join the video meeting thursday 9.20.
