### ISSUE TITLE
Request for "rulesets" feature, is it a required service?

### ISSUE THREAD

**Issue by janhalen** [OS2fleetoptimiser/project-setup#14]
@andreasDroid: We have recieved a "request" from GitHub on a paid tuleset feature. Was that just a test or is it a neede feature for the pipelines?

**Comment by andreasDroid** [comment]
@janhalen , I'm not aware. Probably not something deliberate, so I guess you can just discard it.

**Comment by janhalen** [comment]
thanks for a superfast answer!
