### ISSUE TITLE
🔒 Set Up Automated Security and Code Scanning

### ISSUE THREAD

**Issue by janhalen** [OS2fleetoptimiser/project-setup#4]
## 🔒 Automated Security and Code Scanning to maintain robust and secure codebases

*To proactively identify and mitigate security vulnerabilities and code quality issues, ensure robust and secure codebases, and maintain high standards of code quality, a set of automated security and code scanning tools should be configured in the repositories*

- [x] Create a GitHub Actions workflow file 
- [x] Configure security scanning: Enable builtin tools like e.g. [CodeQL](https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql) for security analysis.
- [x] Configure code quality scanning: Setup linter tools relevant to the type of source-code contributions.
- [x] Set up notifications: Ensure that alerts and reports are sent to the appropriate channels (e.g., email, zulip etc.).
- [x] Test the workflow: Run the workflow to ensure it correctly identifies issues and generates reports.
- [x] Integrate into PR workflow: Consider integration the checks in a pull request workflow to automate the work further.

**Comment by janhalen** [comment]
@andreasDroid, some of these tasks have been adressed in the initial merge https://github.com/OS2fleetoptimiser/OS2fleetoptimiser/pull/1.

Lets discuss what is needed and get them ticked off

**Comment by andreasDroid** [comment]
@janhalen , is it too early to make the repo public? Asking in order to be able to pull the automated build images for the test env? 

We're happy to implement more checks on the code, both quality and security wise. 
I'm a bit uncertain if the "Test the workflow" is satisifed or if it's in relation with the additional code checks.

**Comment by janhalen** [comment]
The more transparent, the better..

We'll improve it in public 🙂

**Comment by andreasDroid** [comment]
Great, if we manage to make it public today, I'll be able to pull the first os2fleetoptimiser image (🕺) and PO will be able to test the env tomorrow.

**Comment by janhalen** [comment]
I'll just go ahead an flick the switch then!

**Comment by janhalen** [comment]
@andreasDroid aaand were public!

**Comment by andreasDroid** [comment]
great!! Test env is running with the `1.20.0-rc.initial-commit-3` build

**Comment by janhalen** [comment]
> I'm a bit uncertain if the "Test the workflow" is satisifed or if it's in relation with the additional code checks.

@andreasDroid. I agree its a bit unclear, what i mean is.. "After we have decided to add linters, and CodeQL and other tests to automate the QA of the build process, we should test that it works and delivers value to the project".. Somthing like that.

I think we should dip our toes in the built in CodeQL for starters (but thats just one quick suggestion, e.g. snyk is also a possibility and many others) .. and add a simple linter for python and typescript and then see how that affects your flow...

**Comment by andreasDroid** [comment]
@janhalen , do you have a suggestion where this workflow should live? I.e. specific branches or tags? Along with other workflows?

**Comment by andreasDroid** [comment]
we're getting a lot of workflows already, so I try to summarise which we have, and their responsibility

| **workflow**           | **trigger**                  | **branch/tag**        | **responsibility**                                |
|-------------------------|------------------------------|---------------------|----------------------------------------|
| **CodeQL**              | `push`, `pull_request`, | `main`, `develop`   | security |
| **Python Linter**       | `push`, `pull_request`       | `*` |  check coding standard  |
| **TypeScript Linter**   | `push`, `pull_request`       | `*` | check coding standard |
| **build frontend** | `push`                       | `*`        | test |
| **build backend** | `push`                       | `*`        | test |
| **push frontend** | `push`                       | `v tags`        | build stable |
| **push fackend**  | `push`                       | `v tags`        | build stable |
| **testing workflow**    | `push`                 | `v rc tags`  |  validate and push to test env |

how does this look to you, @janhalen ?

**Comment by janhalen** [comment]
> @janhalen , do you have a suggestion where this workflow should live? I.e. specific branches or tags? Along with other workflows?

I can enable the built in CodeQL in the settings, that will inject a workflow with some settings for us to test out?

**Comment by janhalen** [comment]
> we're getting a lot of workflows already, so I try to summarise which we have, and their responsibility
> **workflow** 	**trigger** 	**branch/tag** 	**responsibility**
> **CodeQL** 	`push`, `pull_request`, 	`main`, `develop` 	security
> **Python Linter** 	`push`, `pull_request` 	`*` 	check coding standard
> **TypeScript Linter** 	`push`, `pull_request` 	`*` 	check coding standard
> **build frontend** 	`push` 	`*` 	test
> **build backend** 	`push` 	`*` 	test
> **push frontend** 	`push` 	`v tags` 	build stable
> **push fackend** 	`push` 	`v tags` 	build stable
> **testing workflow** 	`push` 	`v rc tags` 	validate and push to test env
> 
> how does this look to you, @janhalen ?

Just to be sure, is the build of the container images only triggered for testing? Or am i reading it wrong?

Other than that, it looks fine... maybe it should be included in the official docs, explaning how the project is built and tested?

**Comment by andreasDroid** [comment]
Sounds good to enable the built in codeql. 

- Build is triggered for any branch.
- Build and push for testing is enabled with `v.*rc` tags
- Build and push stable images is eanbled with `v`tags.

**Comment by janhalen** [comment]
👍🏻 CodeQL enabled with default settings, and secrets scaning enabled with default settings..

Read more here: https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql
