### ISSUE TITLE
🔒 Implement Branch Protection Rules and Naming Conventions for Branches

### ISSUE THREAD

**Issue by janhalen** [OS2fleetoptimiser/project-setup#5]
## 🔒 Implement Branch Protection Rules and Naming Conventions for Branches

*To reduce the overhead for developers by minimizing unnecessary PRs for small changes, while maintaining code quality and review processes, a feature-branch and PR flow should be agreed upon and implemented*

https://docs.github.com/en/get-started/using-github/github-flow

**Comment by janhalen** [comment]
@andreasDroid I have protected the main branch in the https://github.com/OS2fleetoptimiser/OS2fleetoptimiser sourcecode repo. 

A proposal for a standardized contribution flow:

Contributions are agreed upon in an issue and signed off by the Product Owner @ Signe (oops she has not yet joined the project 😄 ) a branch for the code is created from this issue (if using the GitHub UI, the naming is pretty straightforward with the issue number and a shortened branch name for the title) Any inputs for the branch naming scheme?

**Comment by andreasDroid** [comment]
Usually, we just use `bug/<descriptive-naming>` and `feature/<descriptive-naming>` for the naming of branches.

**Comment by signe** [comment]
> Contributions are agreed upon in an issue and signed off by the Product Owner @ Signe (oops she has not yet joined the project 😄 )

Just to prevent any errors in the future — This account doesn't belong to anyone associated with this project.

**Comment by janhalen** [comment]
> Just to prevent any errors in the future — This account doesn't belong to anyone associated with this project.

Sorry for the noise, it was a silly human error because of a coincidential name similarity. We have that sorted now.

**Comment by janhalen** [comment]
> Usually, we just use `bug/<descriptive-naming>` and `feature/<descriptive-naming>` for the naming of branches.

@andreasDroid, sounds fine. To make it fully transparent what the code contributions are trying to solve, we would like all branches in the public repo, also to have a reference to a public issue that has been approved for work by the PO.

The simplest and most standardized way i guess is to add the issue-number to the start of the branch-name with a hyphen after.. 

Example.. if **this** issue was approved for work by the PO and there was some feature code to be developed to solve it, the branch would be called _feature/5-implement-branch-protection-rules-and-naming-conventions_

**Comment by andreasDroid** [comment]
Sounds good to me.

**Comment by janhalen** [comment]
I would love to have the PO onboard to sign off on this as it has an impact on the transparency of the projects delivery process..  

But otherwise I'm ready to close this initial issue.
