### ISSUE TITLE
🧬 Setup source-code repository and make first commit

### ISSUE THREAD

**Issue by janhalen** [OS2fleetoptimiser/project-setup#6]
*To get started quickly without too many manual tasks, the standard [OS2 project template](https://github.com/OS2offdig/os2-project-template) should be cloned and used as a starting point for the monorepo source code repository in os2fleetoptimiser*

- [x] Clone template from https://github.com/OS2offdig/os2-project-template as a private repo @janhalen 
- [x]  Make a branch for the source code transfer @janhalen

-  [x]  Make the official transfer of the source code to this branch @andreasDroid 

- [ ] Agree on the initial PR review and make it clear and transparent what the purpose of this large initial commit is. (work in progress here: https://github.com/OS2fleetoptimiser/OS2fleetoptimiser/pull/1)

- [ ]  When @OS2fleetoptimiser/maintainers decides the repo is ready for the public eye, make it public.

- [x] Create initial documentation commit in docs repo

**Comment by andreasDroid** [comment]
Hi @janhalen, I assume this repo is simply used to track issues, and we should be pushing the code to the (for now) private repo: [OS2fleetoptimiser](https://github.com/OS2fleetoptimiser/OS2fleetoptimiser). 

Looking at the OS2 compliance project, they have a dedicated repo for docs. Is that also the intention that the FleetOptimiser project gets a dedicated repo for the documentation?

Confusion stems from the fact that we've been using sphinx directly in code base for generating automated documentation from the docstrings. In addition, we have been playing around with automated swagger documentation for our API code.

**Comment by janhalen** [comment]
Great questions @andreasDroid! 

Let me try to make it a bit clearer.

The seperate repo is created from this template: https://github.com/OS2offdig/os2-docs-template that you are free to use.

The main intention is to offload the task of hosting an online, searchable web edition of the docs into our OS2 Github organisation. Its using jekyll and github pages for achieving this, but there is no limits to where the markdown content can originate from. 

It sounds great to have some of the sources be automated as you describe. I guess the way your pipeline intends to serve the results of your docs needs to be taken into account, but if it is possible to just generate an organised sturcture of markdown files, then just on top of my head, a simple solution could be to add your sphinx doc result folder as a submodule in the docs repo? But lets talk about the possible technical solutions.. 

The goal is to have all the technical docs built and hosted alongside the code in the github, making it independent of any supplier CI or municipality webservers.

**Comment by janhalen** [comment]
@andreasDroid: It seems like progress has stalled, can i be of further assistance with something?

**Comment by andreasDroid** [comment]
All good, @janhalen . We are prioritising the move to OS2 and we will soon (within a couple of weeks) begin to commit code to the repository. I'll reach out, should we have any questions.

**Comment by andreasDroid** [comment]
Hi @janhalen , I don't seem to have write access to https://github.com/OS2fleetoptimiser/OS2fleetoptimiser 
I'm trying to push the initial commit.

**Comment by janhalen** [comment]
> Hi @janhalen , I don't seem to have write access to https://github.com/OS2fleetoptimiser/OS2fleetoptimiser I'm trying to push the initial commit.

Hey @andreasDroid! Are we ready to make the repo public?

We prefer the initial commit to be made in a branch, and then later merged in in a proper PR process to make the source code ownership transfer transparent.

I have made a branch for the code transfer --> https://github.com/OS2fleetoptimiser/OS2fleetoptimiser/tree/source-code-transfer-from-droids-agency

And i have updated the list of tasks for this issue to be done..

**Comment by andreasDroid** [comment]
No, we're not ready to make it public. 
I wanted to start pushing the code, making the documentation right etc. before making it public.
I pushed an initial commit to the source-code branch

**Comment by andreasDroid** [comment]
@janhalen , I've prepared some documentation on this repo
https://github.com/OS2fleetoptimiser/OS2fleetoptimiser-docs/

I assume pages must be enabled, because the deploy pages workflow fails:

https://github.com/OS2fleetoptimiser/OS2fleetoptimiser-docs/actions/workflows/pages.yml

Can you help me with that?

**Comment by janhalen** [comment]
Yup.. Looking into it later today...

**Comment by janhalen** [comment]
@andreasDroid: You were 100% right .. GitHub pages were disabled, because the repo was private... Thats one of the GitHub caveats on our product tier. 🫤 

I made it public, and have made a setup that deploys from ` /docs ` on the master branch..

**Comment by janhalen** [comment]
I have changed the build method to use GH Actions workflows and to deploy from /root... 

@andreasDroid  It seems there are some dependencies missing in the build! ➡️ [Log](https://github.com/OS2fleetoptimiser/OS2fleetoptimiser-docs/actions/runs/11973275597/job/33382044269)

What build method do you prefer? A standard GitHub Action build our are there any requirements in the docs that call for a custom build workflow?

Feel free to adapt the build to fit your purposes, or reach out to me and we can look into making it work with the default flows.

**Comment by andreasDroid** [comment]
@janhalen , thanks.

Ehm.. I don't have any prefered build method :) 
I just copied the template https://github.com/OS2offdig/os2-docs-template 

I re-ran pages flow and it seem to have successfully deployed https://os2fleetoptimiser.github.io/OS2fleetoptimiser-docs/

**Comment by janhalen** [comment]
@andreasDroid: Great stuff.. and its looking good...

Some minor adjustments needed.. but how about moving those issues to the docs repo to improve the relevance and transparency and to make a PR flow easier?

**Comment by andreasDroid** [comment]
Yes, make sense moving related _issues_ to the dedicated docs repo :)
