### ISSUE TITLE
👤 Confirm Access for the Product Owner to the Project

### ISSUE THREAD

**Issue by janhalen** [OS2fleetoptimiser/project-setup#8]
- [x] Investigate whether the PO has a github account, if not assist in creating one.
- [ ] ~~Evaluate and setup the right permissions~~ postponed for later

**Comment by janhalen** [comment]
@andreasDroid : I can investigate this when the PO comes to visit us in OS2

**Comment by sobuos** [comment]
@andreasDroid @janhalen: I have access. I am not sure I have the right permission, but let's take that in another issue if needed
